<script setup>
import {computed,nextTick,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue';
import {usePortal} from '../auth/session.js';
import {createMapsApi} from './maps-api.js';
import {filterMapUsers,mapUser} from './maps-model.js';
import {createMapRenderer} from './maps-renderer.js';
import {errorText} from '../finance/finance-model.js';
import MapUserDetails from './MapUserDetails.vue';
import '../finance/finance-parity.css';
import './maps.css';
const {session}=usePortal(),api=createMapsApi(session.api),canvas=ref(null),popup=ref(null);
const permitted=computed(()=>session.can('map.view')),filters=reactive({query:'',type:'',branch:'',status:'',custom:false,selected:[]});
const users=ref([]),branches=ref([]),selectedId=ref(null),detailsOpen=ref(false),listPage=ref(1),clusterIds=ref([]),tick=ref(0),state=reactive({loading:false,error:'',notice:'',tileError:false,meta:{truncated:false,total_candidates:0,limit:5000}});
let renderer=null,reader,readRevision=0,generation=0,alive=true,initializing=false,timer,pollTimer,serverAt=0,receivedAt=0,popupFocus,initialFit=false;
const serverNow=computed(()=>{tick.value;return serverAt+(performance.now()-receivedAt);});
const rows=computed(()=>filterMapUsers(users.value,filters,branches.value,serverNow.value));
const networks=computed(()=>[...new Map(rows.value.map(user=>[user.networkId,{id:user.networkId,name:user.networkName,color:user.networkColor}])).values()]);
const options=computed(()=>users.value.filter(user=>`${user.name} ${user.account}`.toLocaleLowerCase('ar').includes(filters.query.trim().toLocaleLowerCase('ar'))).slice(0,100));
const pages=computed(()=>Math.max(1,Math.ceil(rows.value.length/30))),listed=computed(()=>rows.value.slice((Math.min(listPage.value,pages.value)-1)*30,Math.min(listPage.value,pages.value)*30));
const scopeIdentity=computed(()=>JSON.stringify([session.state.identity?.user?.id,session.state.identity?.membership,session.state.identity?.permissions]));
async function failure(cause){if(cause.name==='AbortError'||!alive)return;state.error=errorText(cause);if([401,403].includes(cause.status))await session.refresh();}
async function load(){if(!permitted.value)return;reader?.abort();reader=new AbortController();const expected=++readRevision;state.loading=true;state.error='';try{const response=await api.users({},reader.signal);if(!alive||expected!==readRevision)return;users.value=response.data.map(mapUser);branches.value=response.branches||[];state.meta=response.meta;serverAt=Date.parse(response.meta.generated_at);receivedAt=performance.now();tick.value++;await nextTick();renderer?.draw(rows.value,selectedId.value);if(renderer&&rows.value.length&&!initialFit){renderer.fit();initialFit=true;}}catch(cause){if(alive&&expected===readRevision)await failure(cause);}finally{if(alive&&expected===readRevision)state.loading=false;}}
function notify(message){state.notice=message;}
async function initialize(){if(!alive||!permitted.value||renderer||initializing)return;initializing=true;const expected=generation;try{const [leaflet,countries]=await Promise.all([import('leaflet'),import('./map-countries.js'),import('leaflet/dist/leaflet.css')]);await nextTick();if(!alive||expected!==generation||!permitted.value||!canvas.value)return;renderer=createMapRenderer({L:leaflet.default||leaflet,canvas:canvas.value,countries:countries.default,onTileError:value=>{state.tileError=value;},onSelect:user=>{selectedId.value=user.id;clusterIds.value=[];},onDetails:showDetails,notify});renderer.draw(rows.value,selectedId.value);renderer.fit();initialFit=rows.value.length>0;}catch(cause){if(expected===generation)await failure(cause);}finally{initializing=false;if(alive&&permitted.value&&!renderer&&expected!==generation)initialize();}}
function fit(){renderer?.draw(rows.value,selectedId.value);renderer?.fit();}
function choose(user){selectedId.value=user.id;detailsOpen.value=false;clusterIds.value=[];renderer?.choose(user);}
async function showDetails(user){popupFocus=document.activeElement;selectedId.value=user.id;detailsOpen.value=true;clusterIds.value=[];listPage.value=Math.floor(rows.value.findIndex(row=>row.id===user.id)/30)+1;renderer?.choose(user,false);await nextTick();const element=popup.value?.$el||popup.value;const target=Array.isArray(element)?element.at(-1)?.$el||element.at(-1):element;target?.focus({preventScroll:true});}
async function closeUserPopup(){detailsOpen.value=false;await nextTick();if(popupFocus?.isConnected)popupFocus.focus();}
async function reset(){Object.assign(filters,{query:'',type:'',branch:'',status:'',custom:false,selected:[]});selectedId.value=null;detailsOpen.value=false;await nextTick();fit();}
watch(()=>JSON.stringify(filters),()=>{listPage.value=1;clusterIds.value=[];});
watch(rows,async()=>{if(!rows.value.some(row=>row.id===selectedId.value)){selectedId.value=null;detailsOpen.value=false;}listPage.value=Math.min(listPage.value,pages.value);await nextTick();renderer?.draw(rows.value,selectedId.value);});
watch(scopeIdentity,()=>{generation++;readRevision++;reader?.abort();users.value=[];branches.value=[];selectedId.value=null;detailsOpen.value=false;initialFit=false;renderer?.dispose();renderer=null;if(permitted.value){load();initialize();}});
onMounted(()=>{load();initialize();timer=setInterval(()=>{if(document.visibilityState==='visible')tick.value++;},15000);pollTimer=setInterval(()=>{if(document.visibilityState==='visible')load();},60000);});
onBeforeUnmount(()=>{alive=false;generation++;readRevision++;reader?.abort();clearInterval(timer);clearInterval(pollTimer);renderer?.dispose();renderer=null;users.value=[];branches.value=[];});
</script>

<template>
  <section class="finance-workspace"><section v-if="permitted" class="card user-map-page"><div class="support-section-heading"><h2>خريطة الحسابات والمستخدمين</h2></div><p v-if="state.error" class="notice warn" role="alert">{{state.error}} <button class="btn small" :disabled="state.loading" @click="load">إعادة المحاولة</button></p><p v-if="state.notice" class="notice" role="status">{{state.notice}}</p><p v-if="state.meta.truncated" class="notice warn">تظهر أول {{state.meta.limit}} من {{state.meta.total_candidates}} مستخدم ضمن نطاقك. البحث والفلترة يطبّقان على القائمة المعروضة.</p>
    <div class="user-map-filters"><label>بحث<input v-model="filters.query" placeholder="اسم المستخدم أو الحساب" aria-label="بحث مستخدمي الخريطة"></label><label>نوع الحساب<select v-model="filters.type"><option value="">الكل</option><option value="main">وكيل رئيسي</option><option value="sub">فرع</option><option value="pos">نقطة بيع</option><option value="employee">الموظفون</option></select></label><label>الحساب وتابعوه<select v-model="filters.branch"><option value="">كل النطاق المسموح</option><option v-for="branch in branches" :key="branch.id" :value="branch.id">{{branch.name}}</option></select></label>
    <div class="map-connection-filter"><span>حالة الاتصال</span><div role="group" aria-label="فلترة حالة الاتصال"><button class="btn" :aria-pressed="filters.status===''" @click="filters.status=''">الكل</button><button class="btn" :aria-pressed="filters.status==='online'" @click="filters.status='online'"><i class="map-status-dot online" aria-hidden="true"></i>متصل</button><button class="btn" :aria-pressed="filters.status==='offline'" @click="filters.status='offline'"><i class="map-status-dot" aria-hidden="true"></i>غير متصل</button></div></div><button class="btn" :aria-pressed="filters.custom" @click="filters.custom=!filters.custom">اختيار مخصص ({{filters.selected.length}})</button><button class="btn" @click="reset">عرض الكل</button><button class="btn primary map-fit-results" @click="fit">عرض نتائج البحث ({{rows.length}})</button></div>
    <div v-if="filters.custom" class="map-custom"><div><label v-for="user in options" :key="user.id"><input type="checkbox" v-model="filters.selected" :value="user.id">{{user.name}} · {{user.kindLabel}}</label></div><p v-if="!filters.selected.length" class="caption">اختر مستخدمًا</p></div><div class="map-network-legend"><span v-for="network in networks" :key="network.id"><i :style="{backgroundColor:network.color}"></i>{{network.name}}</span></div><div class="map-legend"><span>🟢 متصل</span><span>⚪ غير متصل</span><span>◆ وكيل · ■ فرع · ▲ نقطة · ● موظف</span></div>
    <div v-if="state.tileError" class="notice">تعذر تحميل بعض أجزاء الخريطة <button class="btn small" @click="renderer?.retryTiles()">إعادة المحاولة</button></div><div class="user-map-layout"><div class="map-display"><div ref="canvas" class="user-map-canvas" aria-label="خريطة مواقع المستخدمين"></div></div><aside class="map-people"><div v-if="clusterIds.length"><b>مستخدمون في المواقع المتقاربة</b><button v-for="user in rows.filter(user=>clusterIds.includes(user.id))" :key="user.id" class="map-person" @click="choose(user)">{{user.name}} · {{user.kindLabel}}</button></div><h3>المستخدمون · {{rows.length}}</h3>
    <div v-for="user in listed" :key="user.id" class="map-person-row" :class="{'details-visible':selectedId===user.id&&detailsOpen}" :style="{'--network-color':user.networkColor}"><button class="map-person" :class="{selected:selectedId===user.id}" @click="choose(user)"><span>{{user.online?'🟢':'⚪'}} {{user.name}}</span><small>{{user.kindLabel}} · {{user.account}}</small><small>{{user.source}}</small></button><button class="btn small map-details-button" @click="showDetails(user)" :aria-label="'تفاصيل '+user.name">التفاصيل</button><MapUserDetails v-if="selectedId===user.id&&detailsOpen" ref="popup" :user="user" @close="closeUserPopup" /></div><p v-if="!rows.length" class="empty">{{state.loading?'جارٍ التحميل…':'لا توجد نتائج مطابقة'}}</p><div class="map-paging"><button class="btn small" :disabled="listPage<=1" @click="listPage--">السابق</button><span>{{Math.min(listPage,pages)}} / {{pages}}</span><button class="btn small" :disabled="listPage>=pages" @click="listPage++">التالي</button></div></aside></div>
  </section><div v-else class="card empty">ليس لديك صلاحية عرض المواقع</div></section>
</template>
