<script setup>
import {computed,inject,reactive,ref,watch} from 'vue';
import {accountTypes,emptyFilters,financeKey,matchesAccount} from './finance-model.js';
import FinanceDialog from './FinanceDialog.vue';
const props=defineProps({open:Boolean}),emit=defineEmits(['close']),vm=inject(financeKey),draft=reactive(emptyFilters()),error=ref('');
const cities=computed(()=>[...new Set(vm.options.accounts.map(row=>row.city || row.governorate_name).filter(Boolean))]);
const kinds=computed(()=>[...new Set(vm.options.accounts.map(row=>row.type))]);
const networks=computed(()=>vm.options.accounts.filter(row=>row.type==='main_agent'));
const choices=computed(()=>vm.options.accounts.filter(row=>matchesAccount(row,{...draft,account:''},vm.options.accounts)));
watch(()=>props.open,open=>{if(open){Object.assign(draft,vm.filters);error.value='';}});
watch(choices,rows=>{if(draft.account && !rows.some(row=>Number(row.id)===Number(draft.account)))draft.account='';});
function apply(){if(draft.from && draft.to && draft.from>draft.to){error.value='تاريخ البداية يجب أن يسبق تاريخ النهاية.';return;}Object.assign(vm.filters,draft);emit('close');}
</script>
<template><FinanceDialog :open="open" title="فلترة وبحث" @close="emit('close')"><form @submit.prevent="apply"><div class="formgrid"><label>المحافظة<select v-model="draft.city" aria-label="المحافظة"><option value="">الكل ضمن نطاقي</option><option v-for="city in cities" :key="city">{{city}}</option></select></label><label>نوع الحساب<select v-model="draft.kind" aria-label="نوع الحساب"><option value="">الكل ضمن نطاقي</option><option v-for="kind in kinds" :key="kind" :value="kind">{{accountTypes[kind] || kind}}</option></select></label><label v-if="networks.length">شبكة الوكيل<select v-model="draft.network" aria-label="شبكة الوكيل"><option value="">الكل ضمن نطاقي</option><option v-for="row in networks" :key="row.id" :value="row.id">{{row.name}}</option></select></label><label>حالة الحساب<select v-model="draft.active" aria-label="حالة الحساب"><option value="">الكل ضمن نطاقي</option><option value="active">مفعّل</option><option value="inactive">معطّل</option></select></label><label>بحث بالاسم أو الهاتف<input v-model="draft.query" type="search"></label><label>الحساب<select v-model="draft.account" aria-label="الحساب"><option value="">الحسابات المطابقة ضمن نطاقي</option><option v-for="row in choices" :key="row.id" :value="row.id">{{row.name}} · {{accountTypes[row.type] || row.type}}</option></select></label><label class="full">رقم الحركة أو المرجع<input v-model="draft.reference" type="search"></label><label>من تاريخ<input v-model="draft.from" type="date" :max="draft.to || undefined"></label><label>إلى تاريخ<input v-model="draft.to" type="date" :min="draft.from || undefined"></label></div><p class="caption">التاريخ والمرجع للسجلات؛ الأرصدة المعروضة حالية.</p><p v-if="error" class="notice warn" role="alert">{{error}}</p><div class="formfoot"><button type="button" class="btn" @click="Object.assign(draft,emptyFilters());error=''">مسح الاختيارات</button><button type="button" class="btn" @click="emit('close')">إلغاء</button><button class="btn primary">تطبيق</button></div></form></FinanceDialog></template>
