<script setup>
import TablePanel from '../../shared/components/TablePanel.vue';

import { computed, inject, ref, watch } from 'vue';
import { accountTypes, financeKey, money } from './finance-model.js';
import FinanceDialog from './FinanceDialog.vue';
const vm=inject(financeKey), emit=defineEmits(['movements']), query=ref(''), type=ref(''), size=ref(10), page=ref(1), detail=ref(null);
const filtered=computed(()=>vm.accounts.value.filter(row=>(!type.value || row.type===type.value) && (!query.value || `${row.name} ${row.phone || ''}`.toLocaleLowerCase('ar').includes(query.value.trim().toLocaleLowerCase('ar')))));
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/size.value))), shown=computed(()=>filtered.value.slice((page.value-1)*size.value,page.value*size.value));
watch([query,type,size,vm.accounts],()=>{page.value=1;detail.value=null;});
const kinds=computed(()=>[...new Set(vm.accounts.value.map(row=>row.type))]);
function movements() { const id=detail.value.id; detail.value=null; emit('movements',id); }
</script>
<template><section class="card wallet-accounts-table" data-no-pagination><div class="cardhead"><h3>الحسابات والأرصدة</h3><button class="btn" @click="vm.showFilters.value=true">فلترة وبحث</button></div><div class="wallet-account-tools"><input v-model="query" type="search" placeholder="بحث باسم الحساب أو الهاتف" aria-label="بحث الحسابات"><select v-model="type" aria-label="نوع الحساب في الجدول"><option value="">كل الأنواع ضمن نطاقي</option><option v-for="kind in kinds" :key="kind" :value="kind">{{accountTypes[kind] || kind}}</option></select><label>عرض<select v-model.number="size" aria-label="عدد الحسابات في الصفحة"><option v-for="number in [10,25,50,100]" :key="number" :value="number">{{number}}</option></select></label></div><p class="caption">عدد الحسابات المطابقة: {{vm.loading.value ? "—" : filtered.length}}</p><TablePanel :start="(page-1)*size+1" class="tablewrap"><table><thead><tr><th>الحساب</th><th>النوع</th><th>تابع إلى</th><th>الرصيد المتاح</th><th>الإجراء</th></tr></thead><tbody><tr v-for="row in shown" :key="row.id"><td>{{row.name}}</td><td>{{accountTypes[row.type] || row.type}}</td><td>{{row.parent_id?vm.name(row.parent_id):'—'}}</td><td>{{money(vm.walletAmount(row.id,vm.service.value,vm.currency.value))}} {{vm.currencyLabel(vm.currency.value)}}</td><td><button class="btn small" @click="detail=row">عرض التفاصيل</button></td></tr><tr v-if="!filtered.length && !vm.loading.value"><td colspan="5" class="empty">لا توجد حسابات مطابقة</td></tr></tbody></table></TablePanel><div class="table-pagination-footer"><button class="btn small" :disabled="page<=1" @click="page--">السابق</button><span>الصفحة {{page}} من {{pages}}</span><button class="btn small" :disabled="page>=pages" @click="page++">التالي</button></div></section>
  <FinanceDialog :open="!!detail" :title="detail?.name || 'تفاصيل الحساب'" @close="detail=null"><template v-if="detail"><dl class="account-fields"><div><dt>النوع</dt><dd>{{accountTypes[detail.type] || detail.type}}</dd></div><div><dt>تابع إلى</dt><dd>{{detail.parent_id?vm.name(detail.parent_id):'—'}}</dd></div><div><dt>المحافظة</dt><dd>{{detail.city || detail.governorate_name || '—'}}</dd></div><div><dt>الحالة</dt><dd>{{detail.status==='active'?'مفعّل':detail.status?'معطّل':'—'}}</dd></div><div><dt>الرصيد الحالي</dt><dd>{{money(vm.walletAmount(detail.id,vm.service.value,vm.currency.value,'balance'))}} {{vm.currencyLabel(vm.currency.value)}}</dd></div><div><dt>الرصيد المتاح</dt><dd>{{money(vm.walletAmount(detail.id,vm.service.value,vm.currency.value))}} {{vm.currencyLabel(vm.currency.value)}}</dd></div></dl><div class="formfoot"><button class="btn" @click="detail=null">إغلاق</button><button v-if="vm.can('ledger.view')" class="btn primary" @click="movements">عرض حركاته</button></div></template></FinanceDialog>
</template>
