<script setup>
import TablePanel from '../../shared/components/TablePanel.vue';

import { vMoney } from './money-input.js';
import {computed,inject,onBeforeUnmount,reactive,ref,watch} from 'vue';
import {accountTypes,amount,decimal,downloadRows,errorText,financeKey,matchesAccount,minor,money,positive,sum,transferRows} from './finance-model.js';
import FinanceDialog from './FinanceDialog.vue';
const vm=inject(financeKey),query=ref(''),selected=ref([]),drafts=reactive({}),reference=ref(''),text=ref(''),reading=ref(false),preview=ref(null),result=ref(null),from=ref(vm.admin.value?'':vm.ownId.value),importedRows=ref([]),key=vm.key();
let importRevision=0;
onBeforeUnmount(()=>{importRevision++;});
const funders=computed(()=>vm.options.accounts.filter(row=>['main_agent','sub_agent','sub_branch'].includes(row.type) && row.status==='active' && (vm.admin.value || row.id===vm.ownId.value)));
const choices=computed(()=>vm.options.accounts.filter(row=>from.value && row.id!==Number(from.value) && row.status==='active' && matchesAccount(row,{network:from.value},vm.options.accounts)));
const recipients=computed(()=>choices.value.filter(row=>!query.value || `${row.name} ${row.city || ''}`.toLocaleLowerCase('ar').includes(query.value.trim().toLocaleLowerCase('ar'))));
const available=computed(()=>from.value?vm.walletAmount(from.value,vm.service.value,vm.currency.value):null);
watch(funders,rows=>{if(!rows.some(row=>row.id===Number(from.value)))from.value=rows[0]?.id || '';},{immediate:true});
function clear(){selected.value=[];Object.keys(drafts).forEach(id=>delete drafts[id]);text.value='';importedRows.value=[];preview.value=null;result.value=null;key.clear();}
watch(from,()=>{importRevision++;clear();});
watch([vm.service,vm.currency],()=>{importRevision++;preview.value=null;result.value=null;});
function importRows(rows){const incoming=[],amounts={},keys=new Set();for(const cells of rows){if(!cells.some(Boolean))continue;if(/^(?:المستفيد|معرف|account_id|to_account_id)$/i.test(String(cells[0]).trim()))continue;const id=Number(cells[0]),service=cells[2] || vm.service.value,currency=cells[4] || vm.currency.value;if(!Number.isSafeInteger(id) || !choices.value.some(account=>account.id===id))throw new Error(`المستفيد ${cells[0]} غير متاح للتمويل.`);if(!vm.options.services.some(row=>row.id===service) || !vm.options.currencies.includes(currency))throw new Error('المحفظة أو العملة في الملف غير متاحة.');const identity=`${id}:${service}:${currency}`;if(keys.has(identity))throw new Error(`المستفيد #${id} مكرر في المحفظة نفسها.`);keys.add(identity);const value=amount(cells[1]);incoming.push({to_account_id:id,amount:value,service,currency,...(cells[3]?{reference:cells[3]}:{})});amounts[id]=value;}if(!incoming.length || incoming.length>100)throw new Error('القائمة يجب أن تحتوي من 1 إلى100 صف.');importedRows.value=incoming;selected.value=[...new Set(incoming.map(row=>row.to_account_id))];Object.keys(drafts).forEach(id=>delete drafts[id]);Object.assign(drafts,amounts);}
async function readFile(event){const file=event.target.files?.[0];event.target.value='';if(!file || reading.value || vm.busy.value)return;reading.value=true;vm.error.value='';const revision=importRevision;try{const {readImportFile}=await import('../../shared/files/import-reader.js');const sheets=await readImportFile(file);if(revision!==importRevision)throw new Error('تغير الممول أو المحفظة أو الصفحة؛ أعد الاستيراد.');importRows(sheets.flatMap(sheet=>sheet.rows));text.value='';}catch(failed){if(revision===importRevision)vm.error.value=errorText(failed);}finally{reading.value=false;}}
async function prepare(){vm.error.value='';try{if(!from.value)throw new Error('اختر الوكيل الممول.');if(!vm.service.value)throw new Error('اختر محفظة محددة للتمويل.');if(text.value.trim()){const {delimited}=await import('../../shared/files/import-reader.js');importRows(delimited(text.value));}if(!reference.value.trim())throw new Error('أدخل مرجع المجموعة.');const rows=importedRows.value.length?importedRows.value:transferRows(selected.value,drafts,choices.value),groups=new Map();for(const row of rows){const service=row.service || vm.service.value,currency=row.currency || vm.currency.value,id=`${service}:${currency}`;if(!groups.has(id))groups.set(id,{service,currency,values:[]});groups.get(id).values.push(row.amount);}const balances=[...groups.values()].map(row=>{const available=vm.walletAmount(from.value,row.service,row.currency);if(available===null)throw new Error('تعذر التحقق من الرصيد؛ أعد تحديث المحافظ.');const total=sum(row.values);return{service:row.service,currency:row.currency,total,available,remaining:decimal(minor(available)-minor(total))};});preview.value={rows:rows.map(row=>({...row})),from:Number(from.value),service:vm.service.value,currency:vm.currency.value,reference:reference.value.trim(),balances,valid:balances.every(row=>minor(row.remaining)>=0n)};}catch(failed){vm.error.value=errorText(failed);}}
async function confirm(){if(!preview.value?.valid)return;const payload={from_account_id:preview.value.from,service:preview.value.service,currency:preview.value.currency,reference:preview.value.reference,rows:preview.value.rows};const response=await vm.execute(payload,key,body=>vm.api.create('bulk-transfers',body),'تم تنفيذ مجموعة التمويل.');if(response){result.value={...preview.value,response:response.data};preview.value=null;selected.value=[];Object.keys(drafts).forEach(id=>delete drafts[id]);text.value='';importedRows.value=[];await vm.refresh();}}
function downloadPreview(data=preview.value || result.value){if(!data)return;downloadRows('masal-funding.csv',[['المستفيد','المحفظة','المبلغ','العملة','مرجع الطلب','النتيجة','السبب','رقم العملية'],...data.rows.map(row=>{const transfer=data.response?.find(item=>item.to_account_id===row.to_account_id && item.service===(row.service || data.service) && item.currency===(row.currency || data.currency));return[vm.name(row.to_account_id),vm.serviceName(row.service || data.service),row.amount,row.currency || data.currency,row.reference || data.reference,transfer?'منفذ':'معاينة',data.valid?'':'الرصيد لا يكفي لكامل المجموعة',transfer?.transaction_id ?? ''];})]);}
</script>
<template><div class="card"><label>الممول<select v-model="from" aria-label="الممول للتمويل المتعدد" :disabled="vm.busy.value"><option v-for="row in funders" :key="row.id" :value="row.id">{{row.name}}</option></select></label><label>بحث باسم المستفيد<input v-model="query" placeholder="اسم النقطة أو الوكيل أو المحافظة"></label><p class="help">حدد المستفيدين وأدخل مبلغ كل واحد، ثم اضغط معاينة المجموعة. المحفظة المستخدمة: {{vm.serviceName(vm.service.value) || 'اختر محفظة'}}.</p><TablePanel class="tablewrap" style="max-height:420px;overflow:auto"><table class="bulk-recipient-table"><thead><tr><th>اختيار</th><th>المستفيد</th><th>النوع</th><th>المبلغ • {{vm.currencyLabel(vm.currency.value)}}</th></tr></thead><tbody><tr v-for="row in recipients" :key="row.id"><td><input v-model="selected" type="checkbox" :value="row.id" :aria-label="'اختيار '+row.name" @change="text='';importedRows=[]"></td><td>{{row.name}}</td><td>{{accountTypes[row.type] || row.type}}</td><td><input v-model="drafts[row.id]" type="text" inputmode="decimal" v-money :disabled="!selected.includes(row.id) || vm.busy.value" :aria-label="'مبلغ '+row.name" placeholder="أدخل المبلغ" @input="importedRows=[];text=''"></td></tr><tr v-if="!recipients.length"><td colspan="4" class="empty">لا توجد جهات مطابقة متاحة للتمويل.</td></tr></tbody></table></TablePanel><p>المستفيدون المحددون: {{selected.length}}</p><p v-if="importedRows.length" class="caption">{{importedRows.length}} صف مستورد؛ معاينة المجموعة تعرض المحفظة والعملة لكل صف.</p><label>مرجع الطلب / المجموعة<input v-model="reference" maxlength="200" required></label><details><summary>استيراد قائمة من ملف — اختياري</summary><label>استيراد المستفيد، المبلغ، المحفظة، مرجع الطلب<input type="file" accept=".xlsx,.csv,.txt,.tsv" :disabled="reading || vm.busy.value" @change="readFile"></label><textarea v-model="text" dir="ltr" rows="5" placeholder="12,25000&#10;15,50000" @input="selected=[];importedRows=[]"></textarea></details><div class="actions"><button class="btn primary" :disabled="vm.busy.value || reading" @click="prepare">{{reading?'جارٍ قراءة الملف…':'معاينة المجموعة'}}</button><button class="btn" :disabled="vm.busy.value" @click="clear">بدء مجموعة جديدة</button></div><section v-if="result" class="funding-group-result"><div class="rowline"><strong>تم تنفيذ التمويل · {{result.rows.length}} مستفيد</strong><span><span v-for="balance in result.balances" :key="balance.service+balance.currency">{{vm.serviceName(balance.service)}}: {{money(balance.total)}} {{vm.currencyLabel(balance.currency)}}</span></span><button class="btn" @click="downloadPreview(result)">تنزيل النتائج</button></div><div v-for="row in result.rows" :key="row.to_account_id+':'+(row.service || preview?.service || result?.service)+':'+(row.currency || preview?.currency || result?.currency)" class="rowline"><span>{{vm.name(row.to_account_id)}}</span><span>{{money(row.amount)}} {{vm.currencyLabel(row.currency || result.currency)}} · منفذ</span></div></section></div>
  <FinanceDialog :open="!!preview" title="معاينة مجموعة التمويل" :busy="vm.busy.value" @close="preview=null"><template v-if="preview"><p><b>الممول:</b> {{vm.name(preview.from)}}</p><TablePanel class="tablewrap"><table><thead><tr><th>المستفيد</th><th>المحفظة</th><th>المبلغ</th><th>مرجع الطلب</th><th>الفحص</th></tr></thead><tbody><tr v-for="row in preview.rows" :key="row.to_account_id+':'+(row.service || preview?.service || result?.service)+':'+(row.currency || preview?.currency || result?.currency)"><td>{{vm.name(row.to_account_id)}}</td><td>{{vm.serviceName(row.service || preview.service)}}</td><td>{{money(row.amount)}} {{vm.currencyLabel(row.currency || preview.currency)}}</td><td>{{row.reference || preview.reference}}</td><td>صالح</td></tr></tbody></table></TablePanel><div v-for="balance in preview.balances" :key="balance.service+balance.currency" class="rowline"><b>{{vm.serviceName(balance.service)}} · {{vm.currencyLabel(balance.currency)}}</b><span>الإجمالي: {{money(balance.total)}}</span><span>المتاح: {{money(balance.available)}}</span><span>المتبقي: {{money(balance.remaining)}}</span></div><p v-if="vm.error.value" class="notice warn" role="alert">{{vm.error.value}}</p><p v-else-if="!preview.valid" class="notice warn" role="alert">الرصيد لا يكفي لكامل المجموعة</p><div class="actions"><button class="btn primary" :disabled="!preview.valid || vm.busy.value" @click="confirm">تأكيد التمويل</button><button class="btn" @click="downloadPreview()">تنزيل الفحص</button><button class="btn" :disabled="vm.busy.value" @click="preview=null">إلغاء</button></div></template></FinanceDialog>
</template>
