<script setup>
import { computed, reactive } from 'vue';
import ReportModal from './ReportModal.vue';
import { emptyFilters,preset,descendantOf,reportKinds,statusLabels } from './report-model.js';
const props=defineProps({filters:Object,options:Object}); const emit=defineEmits(['close','apply']);
const draft=reactive({...props.filters}); const accounts=computed(()=>props.options.accounts??[]);
const selected=accounts.value.find((a)=>Number(a.id)===Number(draft.agent_id));
const selection=reactive({main:selected?.type==='main_agent'?selected.id:'',branch:selected && selected.type!=='main_agent'?selected.id:''});
function changeMain(){selection.branch='';draft.agent_id=selection.main;draft.pos_id='';}
function changeBranch(){draft.agent_id=selection.branch||selection.main;draft.pos_id='';}
function reset(){Object.assign(draft,emptyFilters());selection.main='';selection.branch='';}
const branches=computed(()=>accounts.value.filter((a)=>['sub_agent','sub_branch'].includes(a.type)&&descendantOf(accounts.value,a.id,selection.main)));
const points=computed(()=>accounts.value.filter((a)=>a.type==='pos'&&descendantOf(accounts.value,a.id,draft.agent_id)));
const products=computed(()=>props.options.products.filter((p)=>(!draft.provider_id||Number(p.provider_id)===Number(draft.provider_id))&&p.currency===draft.currency));
const kinds=computed(()=>reportKinds.filter(([id])=>props.options.sections.some((s)=>s.id.split('-')[0]===id)));
</script>
<template><ReportModal title="إعداد التقرير" @close="emit('close')"><form @submit.prevent="emit('apply',{...draft})"><div class="report-filters"><div class="cardhead"><button type="button" class="btn ghost small" @click="reset">إعادة ضبط</button></div><div class="report-presets"><button v-for="[id,label] in [['today','اليوم'],['week','آخر 7 أيام'],['month','هذا الشهر'],['all','كل الفترات']]" :key="id" type="button" class="btn small" @click="Object.assign(draft,preset(id))">{{label}}</button></div><div class="report-filter-grid"><label>من<input type="date" v-model="draft.from" :max="draft.to||undefined"/></label><label>إلى<input type="date" v-model="draft.to" :min="draft.from||undefined"/></label><label>نوع التقرير<select v-model="draft.kind"><option value="all">التقرير الشامل</option><option v-for="[id,label] in kinds" :key="id" :value="id">{{label}}</option></select></label><label v-if="accounts.some(a=>a.type==='main_agent')">الوكيل الرئيسي<select v-model="selection.main" @change="changeMain"><option value="">كل النطاق المسموح</option><option v-for="a in accounts.filter(a=>a.type==='main_agent')" :key="a.id" :value="a.id">{{a.name}}</option></select></label><label v-if="accounts.some(a=>['sub_agent','sub_branch'].includes(a.type))">الفرع / الفرع الفرعي<select v-model="selection.branch" @change="changeBranch"><option value="">جميع الفروع ضمن النطاق</option><option v-for="a in branches" :key="a.id" :value="a.id">{{a.name}} · {{a.type==='sub_branch'?'فرع فرعي':'فرع'}}</option></select></label><label>نقطة البيع<select v-model="draft.pos_id"><option value="">الكل ضمن نطاقي</option><option v-for="a in points" :key="a.id" :value="a.id">{{a.name}}</option></select></label><label>الفئة<select v-model="draft.product_id"><option value="">الكل ضمن نطاقي</option><option v-for="p in products" :key="p.id" :value="p.id">{{p.name}}</option></select></label><label>الشركة<select v-model="draft.provider_id" @change="draft.product_id=''"><option value="">الكل ضمن نطاقي</option><option v-for="p in options.providers" :key="p.id" :value="p.id">{{p.name}}</option></select></label><label>المحافظة<select v-model="draft.city"><option value="">الكل ضمن نطاقي</option><option v-for="city in options.cities" :key="city">{{city}}</option></select></label><label>حالة البيع<select v-model="draft.status"><option value="">الكل ضمن نطاقي</option><option v-for="status in ['Print Requested','Print Failed','Printed','Reprinted','Reprint Requested','Delivered']" :key="status" :value="status">{{statusLabels[status]}}</option></select></label></div><p class="help">التاريخ يرشح الحركات. الحالة تخص المبيعات فقط. الفئة والشركة يرشحان المبيعات والمخزون والأسعار. المخزون والشبكة والإعدادات لقطات حالية.</p></div><div class="formfoot"><button type="button" class="btn" @click="emit('close')">إلغاء</button><button class="btn primary">تطبيق إعداد التقرير</button></div></form></ReportModal></template>
