<script setup>
import {onBeforeUnmount,onMounted,reactive,ref} from 'vue';
import {usePortal} from '../auth/session.js';
import {createPagedResource} from '../accounts/paged-resource.js';
import {createMutationKey} from '../finance/finance-model.js';
import {changedNotifications} from './communications.js';
import {companyTime} from '../company/company-model.js';
import {inquiryTrackingUrl} from '../company/inquiry-model.js';
import CompanyInquiryConversation from '../company/CompanyInquiryConversation.vue';
const {session}=usePortal(),emit=defineEmits(['count']),filters=reactive({q:'',status:''}),selected=ref(null),reply=ref(''),busy=ref(false),loadingDetail=ref(false),error=ref(''),success=ref('');
const api=session.api,writer=new AbortController(),replyKey=createMutationKey();let reader,revision=0,alive=true;
async function failure(cause){if(cause.name==='AbortError')return '';error.value=cause.message;return cause.message;}
const resource=createPagedResource((params,signal)=>api.request('/support/site-inquiries?'+new URLSearchParams(Object.entries(params).filter(([,v])=>v!=='')),{signal}),failure),list=resource.state;
async function load(page=1){await resource.load({page,per_page:20,...filters});if(alive)emit('count',list.meta.new_count||0);}
async function open(id){if(busy.value)return;reader?.abort();reader=new AbortController();const expected=++revision;selected.value=null;reply.value='';replyKey.clear();loadingDetail.value=true;error.value='';success.value='';try{const result=await api.request(`/support/site-inquiries/${id}`,{signal:reader.signal});if(alive&&expected===revision)selected.value=result.data;}catch(cause){if(expected===revision)await failure(cause);}finally{if(alive&&expected===revision)loadingDetail.value=false;}}
async function send(){if(busy.value||!selected.value||!reply.value.trim())return;busy.value=true;error.value='';success.value='';const id=selected.value.id,payload={version:selected.value.version,body:reply.value.trim()};try{const result=await api.mutate(`/support/site-inquiries/${id}/replies`,'POST',{...payload,idempotency_key:replyKey.for({id,...payload})},writer.signal);if(alive){selected.value=result.data;reply.value='';replyKey.clear();success.value='تم إرسال الرد إلى صفحة متابعة الزبون.';changedNotifications();await load(list.meta.current_page);}}catch(cause){await failure(cause);}finally{if(alive)busy.value=false;}}
async function review(){if(busy.value||!selected.value)return;busy.value=true;try{const result=await api.mutate(`/support/site-inquiries/${selected.value.id}`,'PATCH',{version:selected.value.version,status:selected.value.status==='new'?'followed':'new'},writer.signal);if(alive){selected.value={...selected.value,...result.data};changedNotifications();await load(list.meta.current_page);}}catch(cause){await failure(cause);}finally{if(alive)busy.value=false;}}
async function copy(){try{await navigator.clipboard.writeText(inquiryTrackingUrl(selected.value.tracking_token));success.value='تم نسخ رابط المتابعة.';}catch{error.value='تعذر النسخ؛ انسخ الرابط من الحقل.';}}
onMounted(load);onBeforeUnmount(()=>{alive=false;revision++;reader?.abort();writer.abort();resource.dispose();});
</script>
<template><section class="site-inquiry-inbox"><form class="site-inquiry-filters" @submit.prevent="load()"><input v-model="filters.q" type="search" placeholder="بحث بالاسم أو وسيلة التواصل أو الرسالة" aria-label="بحث رسائل موقع الشركة" maxlength="200"><select v-model="filters.status" aria-label="حالة رسائل الموقع"><option value="">كل الحالات</option><option value="new">بانتظار الرد</option><option value="followed">تمت المتابعة</option></select><button class="btn">بحث</button><span class="badge">{{list.meta.new_count||0}} جديدة</span></form><p v-if="error" class="notice warn" role="alert">{{error}}</p><p v-if="success" class="notice" role="status">{{success}}</p><div class="support-chat-layout"><aside class="support-chat-list"><button v-for="entry in list.rows" :key="entry.id" type="button" class="support-thread support-chat-item" :class="{unread:entry.status==='new',selected:selected?.id===entry.id}" :disabled="busy" @click="open(entry.id)"><span class="support-chat-item-head"><b>{{entry.name}}</b><span class="badge">{{entry.status==='new'?'جديدة':'تمت المتابعة'}}</span></span><small dir="auto">{{entry.contact}}</small><p class="support-snippet">{{entry.message}}</p><small>{{companyTime(entry.time)}}</small></button><p v-if="list.loading" class="read-loading" role="status">جارٍ تحميل الرسائل…</p><p v-else-if="!list.rows.length" class="empty">لا توجد رسائل مطابقة</p><div v-if="list.meta.last_page>1" class="actions"><button class="btn small" :disabled="list.loading||list.meta.current_page<=1" @click="load(list.meta.current_page-1)">السابق</button><span>{{list.meta.current_page}} / {{list.meta.last_page}}</span><button class="btn small" :disabled="list.loading||list.meta.current_page>=list.meta.last_page" @click="load(list.meta.current_page+1)">التالي</button></div></aside><div><CompanyInquiryConversation v-model="reply" :entry="selected" :loading="loadingDetail" :busy="busy" :can-reply="session.can('support.reply')" @reply="send" @refresh="open(selected.id)"/><footer v-if="selected" class="site-inquiry-tools"><label>رابط متابعة الزبون<input :value="inquiryTrackingUrl(selected.tracking_token)" readonly dir="ltr" aria-label="رابط متابعة الزبون"></label><button type="button" class="btn small" @click="copy">نسخ الرابط</button><button v-if="session.can('support.reply')" type="button" class="btn small" :disabled="busy" @click="review">{{selected.status==='new'?'تمت المتابعة':'إعادة فتح'}}</button></footer></div></div></section></template>
