<script setup>
import {computed,ref,watch} from 'vue';
const props=defineProps({accounts:{type:Array,default:()=>[]},modelValue:{type:Array,default:()=>[]}}),emit=defineEmits(['update:modelValue']);
const tab=ref('agents'),query=ref(''),main=ref(''),branch=ref(''),only=ref(false),page=ref(1);
const agents=computed(()=>props.accounts.filter(a=>a.type!=='system'&&a.type!=='pos'));
const mains=computed(()=>agents.value.filter(a=>a.type==='main_agent'));
function within(a,id){const seen=new Set();while(a&&!seen.has(a.id)){if(String(a.id)===String(id))return true;seen.add(a.id);a=props.accounts.find(p=>Number(p.id)===Number(a.parent_id??a.parent?.id));}return false;}
const branches=computed(()=>agents.value.filter(a=>a.type!=='main_agent'&&(!main.value||within(a,main.value))));
function key(a){return props.modelValue.find(k=>k===`agent:${a.id}`||k===`tree:${a.id}`||k===`pos:${a.id}`);}
function toggle(a,checked,coverage='tree'){emit('update:modelValue',[...props.modelValue.filter(k=>k!==`agent:${a.id}`&&k!==`tree:${a.id}`&&k!==`pos:${a.id}`),...(checked?[`${a.type==='pos'?'pos':coverage}:${a.id}`]:[])]);}
const filtered=computed(()=>props.accounts.filter(a=>a.type!=='system'&&(tab.value==='pos'?a.type==='pos':a.type!=='pos')&&(!main.value||within(a,main.value))&&(!branch.value||within(a,branch.value))&&(!only.value||key(a))&&`${a.name} ${a.id}`.includes(query.value.trim())));
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/20))),rows=computed(()=>filtered.value.slice((page.value-1)*20,page.value*20));
watch([tab,query,main,branch,only],()=>page.value=1);watch(main,()=>branch.value='');
</script>
<template><div class="print-scope-picker"><div class="scope-picker-head"><strong>اختيار النطاق</strong><span class="scope-count">{{modelValue.length}} محدد</span></div><div class="scope-picker-tools"><div class="scope-kind-tabs"><button type="button" :class="{active:tab==='agents'}" @click="tab='agents'">الوكلاء والفروع</button><button type="button" :class="{active:tab==='pos'}" @click="tab='pos'">نقاط البيع</button></div><input v-model="query" type="search" placeholder="بحث بالاسم أو المعرّف…" aria-label="بحث بنطاق الطباعة"></div><div class="scope-picker-filters"><label>الوكيل الرئيسي<select v-model="main"><option value="">كل الوكلاء</option><option v-for="a in mains" :value="a.id">{{a.name}}</option></select></label><label>الفرع<select v-model="branch"><option value="">كل الفروع</option><option v-for="a in branches" :value="a.id">{{a.name}}</option></select></label><label class="scope-selected-filter"><input v-model="only" type="checkbox">عرض المختارين فقط</label></div><div class="scope-options scope-card-grid"><article v-for="a in rows" :key="a.id" class="scope-choice-card" :class="{'is-selected':key(a)}"><label class="scope-choice-main"><input type="checkbox" :checked="!!key(a)" :aria-label="'اختيار '+a.name" @change="toggle(a,$event.target.checked)"><span class="scope-choice-text"><strong>{{a.name}}</strong><small>{{a.parent?.name||accounts.find(p=>p.id===a.parent_id)?.name||'وكيل رئيسي'}}</small></span></label><select v-if="key(a)&&a.type!=='pos'" class="scope-coverage" :value="key(a).split(':')[0]" @change="toggle(a,true,$event.target.value)"><option value="tree">مع الفروع ونقاط البيع</option><option value="agent">هذا الحساب فقط</option></select></article><p v-if="!rows.length" class="scope-empty">لا توجد نتائج مطابقة</p></div><div class="scope-pagination"><span>عرض {{filtered.length?(page-1)*20+1:0}}–{{Math.min(page*20,filtered.length)}} من {{filtered.length}}</span><div><button type="button" class="btn small" :disabled="page<=1" @click="page--">السابق</button><span>{{page}} / {{pages}}</span><button type="button" class="btn small" :disabled="page>=pages" @click="page++">التالي</button></div></div></div></template>
